all:
  hosts:
    # Example host configuration
    server1:
      ansible_host: 192.168.1.10
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    
    # Add more hosts as needed
    # server2:
    #   ansible_host: 192.168.1.11
    #   ansible_user: ubuntu
    #   ansible_ssh_private_key_file: ~/.ssh/id_rsa

  children:
    docker_hosts:
      hosts:
        server1:
      vars:
        # Docker-specific variables
        docker_edition: ce
        docker_package: docker-{{ docker_edition }}
        docker_package_state: present
        
    web_servers:
      hosts:
        server1:
      vars:
        # Nginx-specific variables
        nginx_user: www-data
        
    elk_servers:
      hosts:
        server1:
      vars:
        # ELK stack variables
        elasticsearch_heap_size: 1g
        
    app_servers:
      hosts:
        server1:
      vars:
        # Application server variables
        java_packages:
          - openjdk-11-jdk