---
# Minimal Docker Setup - Just the essentials for testing
- name: Minimal Docker Setup
  hosts: docker_hosts
  become: yes
  gather_facts: yes

  tasks:
    - name: Check if Docker is already installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes
      changed_when: false

    - name: Install Docker dependencies (Ubuntu/Debian)
      package:
        name:
          - curl
          - ca-certificates
          - python3-pip
        state: present
      when: ansible_os_family == "Debian" and docker_installed.rc != 0

    - name: Install Docker dependencies (RedHat/CentOS)
      package:
        name:
          - dnf-utils
          - device-mapper-persistent-data
          - lvm2
          - curl
          - ca-certificates
          - python3-pip
        state: present
      when: ansible_os_family == "RedHat" and docker_installed.rc != 0

    - name: Add Docker GPG key (Ubuntu/Debian)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian" and docker_installed.rc != 0

    - name: Add Docker repository (Ubuntu/Debian)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == "Debian" and docker_installed.rc != 0

    - name: Add Docker GPG key (RedHat/CentOS)
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present
      when: ansible_os_family == "RedHat" and docker_installed.rc != 0

    - name: Add Docker repository (RedHat/CentOS)
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes
        state: present
      when: ansible_os_family == "RedHat" and docker_installed.rc != 0

    - name: Install Docker
      package:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: docker_installed.rc != 0

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if Docker Swarm is already initialized
      shell: docker node ls
      register: swarm_status
      changed_when: false
      ignore_errors: yes

    - name: Initialize Docker Swarm using CLI
      shell: docker swarm init --advertise-addr 127.0.0.1 --listen-addr 127.0.0.1:2377
      when: swarm_status.rc != 0
      run_once: true

    - name: Check if test_network exists
      shell: docker network ls | grep test_network
      register: network_exists
      changed_when: false
      ignore_errors: yes

    - name: Create Docker network using CLI
      shell: docker network create --driver overlay --attachable test_network
      when: network_exists.rc != 0
      run_once: true

    - name: Check if test_volume exists
      shell: docker volume ls | grep test_volume
      register: volume_exists
      changed_when: false
      ignore_errors: yes

    - name: Create Docker volume using CLI
      shell: docker volume create test_volume
      when: volume_exists.rc != 0
      run_once: true

    - name: Display minimal Docker setup information
      debug:
        msg: |
          Minimal Docker setup completed using Docker CLI!
          
          Docker Swarm initialized on: 127.0.0.1:2377
          Test network created: test_network (overlay, attachable)
          Test volume created: test_volume
          
          Verification commands:
          - docker node ls
          - docker network ls --filter driver=overlay
          - docker volume ls
          - docker service create --name test-service --network test_network nginx:alpine
          
          Note: Using Docker CLI commands instead of Ansible Docker modules
          to avoid Python Docker SDK dependency issues.